<a href="https://colab.research.google.com/github/AngeloCastilloPerez/PythonBasic/blob/main/Aprende_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hola soy Angelo Castillo 😄, te felicito por querer aprender Python y sus librerías, espero te sirva la siguiente información:

# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

### Características básicas de ndarray

<ul>
<li>Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b></li>
<li>Todos los elementos de un ndarray deben tener <b>EL MISMO TIPO</b>.</li>
<li>El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.</li>
<li>Pero la organización de esos elementos entre diferentes dimensiones sí puede modificarse</li>
</ul>

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1,2,3],[4,5,6]])

# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidim.shape, array_unidim.ndim,  array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim,  array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim,  array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
cero = np.zeros((2,4,3))
cero


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
array_secuencia_1


In [ ]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2


In [ ]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3


In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0,101,5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[7, 6, 5, 1, 7],
       [4, 1, 8, 2, 8]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3,5))
array_3

array([[0.16359775, 0.69563453, 0.06589294, 0.34573   , 0.82009529],
       [0.81023312, 0.66654179, 0.04700611, 0.33322046, 0.76741871],
       [0.58703759, 0.65472238, 0.00512644, 0.99172445, 0.57011526]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)


# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0,10,(3,5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [ ]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [ ]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2,:2]

array([[3, 8],
       [5, 8]])

### Operaciones aritméticas entre ndarrays y escalares

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [ ]:
# Suma
array + 5

In [ ]:
# Resta
array - 2

In [ ]:
# Multiplicación
array * 3

In [ ]:
# División
1 / array

In [ ]:
# División entera
array // 2

In [ ]:
# Potencia
array ** 2

In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0,10,(3,4))
array_6 = np.ones((3,4))

In [ ]:
# invocamos el array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [ ]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))

In [ ]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: ignored

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))

In [ ]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1,5,(3,3))
array_10 = np.random.randint(1,5,(3,3))

In [ ]:
# invocamos el array_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [ ]:
# invocamos el array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [ ]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [ ]:
# Elevamos el array_9 al cuadrado
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [ ]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [ ]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

3.0

In [ ]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [ ]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9,1))

In [ ]:
# invocamos el array_11
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [ ]:
# Transponemos el array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10


array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

### Indexación y slicing basado en secuencias de enteros - Fancy indexing

In [ ]:
array = np.empty((8, 4))
for i in range(8):
    array[i] = i
array

In [ ]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]]

In [ ]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

In [ ]:
array = np.arange(32).reshape((8, 4))
array

**Axis**

Valor 0: Aplicará la función por filas


Valor 1: Aplicará la función por columnas

In [ ]:
array2.sum(axis=1)

In [ ]:
array2.sum(axis=0)

### Operaciones elemento a elemento - Universal functions
El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unitarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [ ]:
array = np.array([1, 2, 3, 4, 5])
np.abs(array)

In [ ]:
np.sign(array)

In [ ]:
np.ceil(array)

# Hola otra vez, te saluda Angelo 😁, eres increible si avanzaste hasta aquí, sigue adelante y seamos expertos en Python!! Vamos!!!
#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [ ]:
array1 = np.random.randn(5, 5)
array1

In [ ]:
array2 = np.random.randn(5, 5)
array2

In [ ]:
np.minimum(array1, array2)

In [ ]:
np.divide(array1,array2)

In [ ]:
np.floor_divide(array1,array2)

### Selección de elementos de ndarrays en función de una condición
NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [ ]:
array1 = np.random.randn(5, 5)
array1

In [ ]:
array2 = np.random.randn(5, 5)
array2

In [ ]:
# Fusión condicional
np.where(array1 < array2, array1, array2)
#entendamos esto como, WHERE(SI ESTO SE CUMPLE,DEVUELVE ESTO, SI NO DEVUELVE ESTO)

In [ ]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)


### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por filas</li>
<li>Valor 1: Aplicará la función por columnas</li>

In [ ]:
array = np.random.randn(5, 4)
array


In [ ]:
# Operación global
np.sum(array)

In [ ]:
# Operación por filas
np.sum(array, axis=0)

In [ ]:
# Operación por columnas
np.sum(array, axis=1)

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [ ]:
# Alguno de los elementos cumple la condición
(array == 0).any()

In [ ]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

### Ordenación de ndarrays

In [ ]:
array = np.random.randn(5, 5)
array

In [ ]:
# Datos ordenados
np.sort(array)

In [ ]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [ ]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

In [ ]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

In [ ]:
np.unique(array1)

In [ ]:
np.union1d(array1, array2)

In [ ]:
np.in1d(array1, array2)

# Eres impresionante 😮, estas devorándote todo Numpy, serás un PRO 🤯! Te felicito, sigue adelante ✨

### Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. Todas estas funciones están disponibles a través del submódulo <b>linalg</b>.

In [ ]:
import numpy as np
import numpy.linalg as linalg

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [ ]:
array1 = np.random.randn(3, 3)
array1

In [ ]:
np.diag(array1)

In [ ]:
array = np.arange(9).reshape(3, 3)
array

In [ ]:
np.dot(array, array)

In [ ]:
linalg.inv(array1)

In [ ]:
linalg.solve(array1,array)

In [ ]:
q, r = linalg.qr(array)
print(q)
print('\n')
print(r)

# Hola soy Angelo y quería decirte que ya estamos por terminar este repaso de Numpy, te deseo éxitos y practica, PRACTICA!, siempre es necesario para no olvidar los aprendido, continuemos 📢

### Generación de números aleatorios

Aunque el core de Pyhton incluye un modulo <b>random</b> para llevar a cabo la generación de números aleatorios, NumPy ofrece una mejora sobre el mismo permitiendo generar directamente ndarrays de valores aleatorios en base a diversas distribuciones. Todas estas funciones están disponibles a través del submódulo <b>random</b>.<br/>

In [ ]:
import numpy as np
import numpy.random as random

Algunas de las más comunes son:
<ul>
<li><b>seed:</b> Establecimiento de semilla del generador de números aleatorios.</li>
<li><b>permutation:</b> Devuelve una permutación aleatoria de una secuencia de entrada (por copia).</li>
<li><b>shuffle:</b> Aplica una permutación aleatoria sobre los elementos de la secuencia de entrada (sin copia).</li>
<li><b>rand:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme.</li>
<li><b>randint:</b> Genera una muestra de números aleatorios enteros dentro de un rango definido.</li>
<li><b>randn:</b> Genera una muestra de números aleatorios utilizando una distribución normal de media 0 y desviación 1.</li>
<li><b>binomial:</b> Genera una muestra de números aleatorios utilizando una distribución binomial.</li>
<li><b>normal:</b> Genera una muestra de números aleatorios utilizando una distribución normal.</li>
<li><b>beta:</b> Genera una muestra de números aleatorios utilizando una distribución beta.</li>
<li><b>chisquare:</b> Genera una muestra de números aleatorios utilizando una distribución chi cuadrado.</li>
<li><b>gamma:</b> Genera una muestra de números aleatorios utilizando una distribución gamma.</li>
<li><b>uniform:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme [0, 1).</li>


</ul>

In [ ]:
random.seed(42)

In [ ]:
random.rand()

In [ ]:
random.randn(5)

In [ ]:
random.binomial(1, 0.5, 10)

In [ ]:
array_per = np.arange(9)
random.permutation(array_per)
array_per


In [ ]:
random.shuffle(array_per)
array_per

# TERMINAMOS 🎈, FELICIDADES Y NO DEJES DE PRACTICAR, SEAMOS MEJORES CADA DÍA!😎